// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inmupnarwelvvutqzoup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlubXVwbmFyd2VsdnZ1dHF6b3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzOTIwNTAsImV4cCI6MjA3MDk2ODA1MH0.lbZr4r7ALr1ODHQ3e2a-li2Ul3-d0t6rdqGfUJjPHws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});